AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Parameters:
  VpcPrefix:
    Description: Select a VPC prefix.
    Type: String

Resources:
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      EndpointConfiguration: REGIONAL
      Domain:
        DomainName: 'mlecar.helloworld.space'
        CertificateArn:
          Fn::ImportValue: !Join ['-', [!Ref VpcPrefix, 'main-certificate']]
        EndpointConfiguration: "REGIONAL"
        Route53:
          HostedZoneId:
            Fn::ImportValue: !Join ['-', [!Ref VpcPrefix, 'zone-id']]
      Auth:
        ApiKeyRequired: false
        ResourcePolicy:
          CustomStatements:
            - Effect: Allow
              Principal: '*'
              Action: 'execute-api:Invoke'
              Resource: 'execute-api:/hello'
          IpRangeWhitelist: ['some-ip']

  HelloWorldLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "hello-world"
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      VpcConfig:
        SubnetIds:
          - Fn::ImportValue: !Join ['-', [!Ref VpcPrefix, 'SubnetPrivateX']]
          - Fn::ImportValue: !Join ['-', [!Ref VpcPrefix, 'SubnetPrivateY']]
        SecurityGroupIds:
          - Fn::ImportValue: !Join ['-', [!Ref VpcPrefix, 'SecurityGroupDefault']]
      Events:
        HelloWorldApi:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
            RestApiId:
              Ref: ApiGateway

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World Lambda function"
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldLambdaFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for HelloWorld Lambda function"
    Value: !GetAtt HelloWorldLambdaFunction.Arn
